### ISSUE TITLE
Copyright infingement

### ISSUE THREAD

**Issue by stormy888** [pluto-net/scinapse-web-client#471]
Your website scinapse.io contains copyrighted content and you are infringing my copyright. I already asked you several times by e-mail to remove my copyrighted content and you failed to remove the content in a period of 2 months.

Would you stop infringing copyright law and comply with my request? I asked you on 5th August and again on 16th September by e-mail. Refusing to comply with GDPR and DMCA is not a way to build a reputable site.

**Comment by TylorShin** [comment]
Sorry for the late answer.
We've been making the backend logic to manage author/paper data.

BTW, our database is mainly based on [MS Academic](https://www.microsoft.com/en-us/research/project/academic/).
If you have a further problem, I recommend contacting them too.
Thanks.
